git:
  depth: false

services:
  - docker

language: c

os: linux
dist: xenial
osx_image: xcode10.1

before_install:
  - sudo ./dist/before_build.sh
  - "./dist/before_build.sh"

script: "./dist/build.sh"

jobs:
  include:
    - os: linux
      stage: webui
      script: "./dist/build_webui.sh"
      env: BUILD_OS="webui"
      dist: bionic
    - os: osx
      stage: build
      env: BUILD_OS="osx"
      osx_image: xcode10.1
    - os: linux
      stage: build
      env: BUILD_OS="windows32"
    - os: linux
      stage: build
      env: BUILD_OS="windows64"
    - os: linux
      stage: build
      env: BUILD_OS="linux"
    - os: linux
      stage: build
      env: BUILD_OS="linuxjack"
    - os: linux
      stage: build
      env: BUILD_OS="ccheck"

stages:
  - webui
  - build

deploy:
  - provider: s3
    access_key_id: "AKIAJ3CDJMCPJXIU5TTA"
    secret_access_key:
      secure: AO/SfGSdeyrMT8/djYgR+TIgnBqggXiW9gaoc208NbcWGfbzgfY3hOse/QSAI7K6qw+sL8HW5i7kf5r6YtHM4g3ProXY5UBF7N7BPjcm1UoPI3W4qOBv2Rr7fX73OhJ+pVjx4jTd+7W87KF4vH5+5DzSfEwgjw4oQxPXEjUj4ZCCeTBMoRas9Qx0h0g+76r9ogXAi9Opke4gp9vz4ONRajaTG+/PPhVGcMlSxEIRgS0S7cqrmpaJ5Dfq4vxjl/eMd2D2LEbC1F2wfegxc2+0aMqlvkmqZYk2rRigZx8ayVasWQGQkX3npgOsy4pRLggn/9d9nt7qqLPkRo/Cd2iGsaNGClTZRiyCc1gN+WIByazQ6RHRYldQhTxOU1VWGk2kR0k+ffMSkIgREc+jGBX/1Upywq2qWK3eyvk6p0h2ynSMdTnxi4c4nJj/4Yp7MGqx/vqjhQmsX/0AGNHSQ49emQOWkCl3AjElmWUJga6vOcXjfugTI0lc816GdufEcKtbTXbOywm86VeLDznwrAcPL+zgZ+HGVjnyb0bGFdJ7B+eLG0pQdut9kxuJKnQH1fstthkBzBA3wJNaoBd0zAH1bgA8cSuXdKaLsn12XfQa05OuLNBaP0Clrdvk7CgPEz7sGqyQxj+tg3QPOTIfQe570UCRo3W7WlMqcRn9PKQV++U=

    bucket: "studio-link-artifacts"
    region: eu-central-1
    local_dir: build/s3_upload
    acl: public_read
    skip_cleanup: true
    on:
      all_branches: true
      condition: $BUILD_OS != ccheck

env:
  global:
    secure: WkYGUGZ3XX88IebmFHtVnPu7arU7cxAmNPIMv3/S6IpWotIdn4/KWocNdKyB7AHJcs/fI/ER+gdZOFHMxLG+6R/lexk1BUv8Okszv9/2Fo1k+Sk5pF1YmTnh3uBagYE4Tm0LE5jA9ZnBt1AlX4ocO51faTEJFACpna5+OpOzxhi3doRbHqACSxFpm4XVxIPKv4ZPR9xQ4wAT1xbg9x2bM6f5XSXxHVN10LkEXN2YeaQVTmg+B+CzJ4ET3M7Yv3jEuysKliAARmz6O+a+WcVmQh9oDfy79AXwbTThKOopD4W18Ed4REpO/y5cvIEXg2cKUtynTLdrlEtpSqFeLIJgx7eAIbQhMMQERx1W+onN/OJB8221KsCPceA4w3k7EBERPr1Fnj/vkrfvWVlQjohjxrVW9kfhgCcpYYemz7PbEC/svSwvzTxUUSM4b8SHnpqf9lr/ydFOl0pwRewVwBnaByPr2ENz1aViFBJXp+Mg1RsUXVb9Q4iNOFW2snN4svOD5+Wi02jIT8xNO94wyC46b607WN9cb9bhl9gNafZr+b/wLR2xCfJzUW4CHoKX5OstNOXUtL6c9b0tOpUCKxO4FoEBClkPsrWSu3af1JkSMaLMJY+73lxk3ABrkmK9Fm6x3/q1oYX7N/SI/KFfdVCYGlNubqrLEzr4xMeuLNkrVvo=
    secure: "BUi0BlIA8qOrdOjAPsR/oGPV96G4VO1lAtXkWSEWN83VzJHoa0Mk6G+ExT06F0t4NxT4JWaj4zTC0MP6TIIwSB7NMtR7VZ0spcCFWpYG5TEhadKyjmLReA38juG7bc7UZX4uFTEgPuFMQF5vGbgeNNTrwlxjavacrVy8KrwNdKJdx4V3JEcK+MGVH01tm/970mrd9McjISPtgFB7u1lDGltD/MAZ92PWjQs/Omb5HJZs/gSWRZSkv9w7ngULEl7LvlOppQP0LiUpi0U+3E3hvP+oPF9rtzyWBbB0rmbRFaJ1pZWTjetM5qt1ObIBoazMHbUect0ifAWNR641TiKzZKvkfFGlNV4KZlBOanZjEWG2V2oeare0gR9FpaLT4suLWT7ZaCqvbGkbF1NFU2aIqnHDwrynbfrbFnOusvrxGxvXEVeCmardqxftZPnwd72GT1I9csSR0lZCpWBbaN3vzI5xuYEhql64XsH4/ru3Xf50ti1zfqovpCXz2JXg188dAnMHCTM9hMyFJTh11CoRQ4IfydzhIMhi2H/O6QKGAoASN0k41wiQ/GXSfAp22aHWLSSZJN7iCwqu53YjkssEQZUCWO3tgBIFwrPyIDduRa6GSlrnMPfe9MU7H0CmkxeZa4yjVTc4whvKR3bEkwul9RyERGeMKEBduamu9bXEUcE="

archlinux:
        packages:
            - wget
            - perl
            - zip
            - unzip
            - vim
            - npm
        script:
            - "./dist/build_windows.sh"
